### ISSUE TITLE
Sketch 3.7.2 - Does not work

### ISSUE THREAD

**Issue by toovy** [romashamin/statemachine-sketch#2]
Hi, I've tried my own example and the downloadable example on the article, but neither one works with the newest Sketch. I've renamed the layer and tried to trigger the hotkey or used the menu "Plugins > State Machine > Update Component", but that also does not work. Seems like something is broke.
BR, toovy

**Comment by romashamin** [comment]
@toovy thank you for the issue.

Yes, it surprisingly stopped working with layers named like `::label`.

While I’m examining what’s going wrong, you could add something to your layer names, like `Something ::label` and the issue will gone.

**Comment by optimix-designer** [comment]
Hi Roman,
Thanks a lot for useful plugin! :)
Unfortunately, it seems that it doesn't work with the latest Sketch 39.1 (31720), neither with labels nor with IDs. 
Can you please check it out? thank you in advance!
