### ISSUE TITLE
Plugin doesn't find layers beginning with the key (::)

### ISSUE THREAD

**Issue by ixley** [romashamin/statemachine-sketch#4]
I just downloaded and tried the example file. The first example seems to work fine, but the second one (Simple Navigation) fails. It appears that id doesn't like when a layer name begins with the key `::`. Adding any characters (even a space) before the key seems to fix this. I'm assuming this was not an expected requirement since it's broken in the example file, so please either file as a bug or clarify the requirement in the documentation.

[Screenshot](https://www.evernote.com/shard/s15/sh/d47ddc32-9135-4a5e-bec5-ada97dc5f5fe/eb528c1e81705b9d)
*This is using Sketch v3.8.3

**Comment by romashamin** [comment]
The issue [is known](https://github.com/romashamin/statemachine-sketch/issues/2#issuecomment-215505015).
