### ISSUE TITLE
The plugin doesn't work with Sketch v39.1

### ISSUE THREAD

**Issue by optimix-designer** [romashamin/statemachine-sketch#5]
Hi Roman,
Thanks a lot for useful plugin! :)
Unfortunately, it seems that it doesn't work with the latest Sketch 39.1 (31720), neither with labels nor with IDs. 
Can you please check it out? Thank you in advance!

**Comment by archetypestudio** [comment]
Same problem. Love this plugin and I use it all the time. Would love an update!

**Comment by romashamin** [comment]
By the way, it’s a great opportunity to improve your coding skills and make Pull Request.

**Comment by optimix-designer** [comment]
Thank you Roman for the fix! :) It's nice to have some kind of Layer Comps in Sketch like in Photoshop.

**Comment by 12people** [comment]
Still not working for me... :(

**Comment by romashamin** [comment]
@12people please make sure you are using latest versions of the plugin and Sketch.

**Comment by 12people** [comment]
Nevermind, it works now. :) (Forgot to restart Sketch after installing the latest version.)
